site_name: Ram's Easy Setup Guide
theme:
name: material
palette:
- scheme: default
toggle:
icon: material/toggle-switch-off-outline
accent: pink
nav:
    - Arch Installation: index.md
    - Gentoo Installation: gentoo.md
    - About: about.md
    - Vim: ./Vim.md
