site_name: Ram's Easy Setup Guide
theme:
    name: material
palette:
    primary: red
    accent: pink
nav:
    - Arch Installation: index.md
    - Gentoo Installation: gentoo.md
    - About: about.md
    - Vim: ./Vim.md
